.TH "antardhvani.du.ac.in.antardhvani.NavigationDrawerFragment" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.antardhvani.NavigationDrawerFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBClickListener\fP"
.br
.ti -1c
.RI "class \fBRecyclerTouchListener\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "View \fBonCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBsetUp\fP (int fragmentId, DrawerLayout drawerLayout, final Toolbar toolbar)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< \fBInformation\fP > \fBgetData\fP ()"
.br
.ti -1c
.RI "static void \fBsaveToPreferences\fP (Context context, String preferenceName, String preferenceValue)"
.br
.ti -1c
.RI "static String \fBreadFromPreferences\fP (Context context, String preferenceName, String defaultValue)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBPREF_FILE_NAME\fP = 'testpref'"
.br
.ti -1c
.RI "static final String \fBKEY_USER_LEARNED_DRAWER\fP = 'user_learned_drawer'"
.br
.ti -1c
.RI "static int \fBin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple \fBFragment\fP subclass\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
