.TH "antardhvani.du.ac.in.Adapter.ScreenSlidePageFragment" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Adapter.ScreenSlidePageFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "View \fBonCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "int \fBgetPageNumber\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBScreenSlidePageFragment\fP \fBcreate\fP (int pageNumber)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBARG_PAGE\fP = 'page'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by lusifer on 13/1/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
