.TH "antardhvani.du.ac.in.Adapter.Group" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Adapter.Group \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "ArrayList< \fBChild\fP > \fBgetItems\fP ()"
.br
.ti -1c
.RI "void \fBsetItems\fP (ArrayList< \fBChild\fP > Items)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
