.TH "antardhvani.du.ac.in.Gcm.GcmIntentService" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Gcm.GcmIntentService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IntentService\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonHandleIntent\fP (Intent intent)"
.br
.ti -1c
.RI "void \fBshowToast\fP (final String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by lusifer on 16/2/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
