.TH "antardhvani.du.ac.in.Database.MyResult" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Database.MyResult \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyResult\fP (String first, String second)"
.br
.ti -1c
.RI "String \fBgetFirst\fP ()"
.br
.ti -1c
.RI "String \fBgetSecond\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by lusifer on 17/2/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
