.TH "antardhvani.du.ac.in.antardhvani.VectorTestActivity" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.antardhvani.VectorTestActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ActionBarActivity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBonCreateOptionsMenu\fP (Menu menu)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (MenuItem item)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
