.TH "antardhvani.du.ac.in.Gcm.GcmRegistrationAsyncTask" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Gcm.GcmRegistrationAsyncTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AsyncTask< Void, Void, String >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGcmRegistrationAsyncTask\fP (Context context)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBstatus\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "String \fBdoInBackground\fP (Void\&.\&.\&.params)"
.br
.ti -1c
.RI "void \fBonPostExecute\fP (String msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by lusifer on 16/2/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
