.TH "antardhvani.du.ac.in.antardhvani.BadgeDrawable" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.antardhvani.BadgeDrawable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Drawable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadgeDrawable\fP (Context context)"
.br
.ti -1c
.RI "void \fBdraw\fP (Canvas canvas)"
.br
.ti -1c
.RI "void \fBsetCount\fP (int count)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (int alpha)"
.br
.ti -1c
.RI "void \fBsetColorFilter\fP (ColorFilter cf)"
.br
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by lusifer on 17/2/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
