.TH "antardhvani.du.ac.in.Adapter.Event_non_competitive_adapter" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Adapter.Event_non_competitive_adapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseExpandableListAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent_non_competitive_adapter\fP (Context context, ArrayList< \fBGroup\fP > groups)"
.br
.ti -1c
.RI "Object \fBgetChild\fP (int groupPosition, int childPosition)"
.br
.ti -1c
.RI "long \fBgetChildId\fP (int groupPosition, int childPosition)"
.br
.ti -1c
.RI "View \fBgetChildView\fP (int groupPosition, int childPosition, boolean isLastChild, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "int \fBgetChildrenCount\fP (int groupPosition)"
.br
.ti -1c
.RI "Object \fBgetGroup\fP (int groupPosition)"
.br
.ti -1c
.RI "int \fBgetGroupCount\fP ()"
.br
.ti -1c
.RI "long \fBgetGroupId\fP (int groupPosition)"
.br
.ti -1c
.RI "View \fBgetGroupView\fP (int groupPosition, boolean isExpanded, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "boolean \fBhasStableIds\fP ()"
.br
.ti -1c
.RI "boolean \fBisChildSelectable\fP (int groupPosition, int childPosition)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
