.TH "antardhvani.du.ac.in.Rules.Rules_competitive" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Rules.Rules_competitive \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "View \fBonCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRules_competitive\fP \fBgetInstance\fP (int position)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by rajanmaurya on 14/2/15\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
