.TH "antardhvani.du.ac.in.Adapter.CardAdapter" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antardhvani.du.ac.in.Adapter.CardAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Adapter< CardAdapter\&.ViewHolder >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBViewHolder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCardAdapter\fP (Context context, ArrayList< String > couponList, ArrayList< String > subTitle)"
.br
.ti -1c
.RI "CardAdapter\&.ViewHolder \fBonCreateViewHolder\fP (ViewGroup parent, int viewType)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (ViewHolder holder, final int position)"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
