.TH "com.example.lusifer.myapplication.backend.registration.model.CollectionResponseRegistrationRecord" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.registration.model.CollectionResponseRegistrationRecord \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GenericJson, and GenericJson\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java\&.util\&.List< \fBRegistrationRecord\fP > \fBgetItems\fP ()"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBsetItems\fP (java\&.util\&.List< \fBRegistrationRecord\fP > items)"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetNextPageToken\fP ()"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBsetNextPageToken\fP (java\&.lang\&.String nextPageToken)"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBset\fP (String fieldName, Object value)"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBclone\fP ()"
.br
.ti -1c
.RI "java\&.util\&.List< \fBRegistrationRecord\fP > \fBgetItems\fP ()"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBsetItems\fP (java\&.util\&.List< \fBRegistrationRecord\fP > items)"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetNextPageToken\fP ()"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBsetNextPageToken\fP (java\&.lang\&.String nextPageToken)"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBset\fP (String fieldName, Object value)"
.br
.ti -1c
.RI "\fBCollectionResponseRegistrationRecord\fP \fBclone\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Model definition for \fBCollectionResponseRegistrationRecord\fP\&.
.PP
This is the Java data model class that specifies how to parse/serialize into the JSON that is transmitted over HTTP when working with the registration\&. For a detailed explanation see: \fChttp://code\&.google\&.com/p/google-http-java-client/wiki/JSON\fP 
.PP
\fBAuthor:\fP
.RS 4
Google, Inc\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "java\&.util\&.List<\fBRegistrationRecord\fP> com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.getItems ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "java\&.util\&.List<\fBRegistrationRecord\fP> com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.getItems ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "java\&.lang\&.String com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.getNextPageToken ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "java\&.lang\&.String com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.getNextPageToken ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBCollectionResponseRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.setItems (java\&.util\&.List< \fBRegistrationRecord\fP > items)"

.PP
\fBParameters:\fP
.RS 4
\fIitems\fP items or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBCollectionResponseRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.setItems (java\&.util\&.List< \fBRegistrationRecord\fP > items)"

.PP
\fBParameters:\fP
.RS 4
\fIitems\fP items or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBCollectionResponseRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.setNextPageToken (java\&.lang\&.String nextPageToken)"

.PP
\fBParameters:\fP
.RS 4
\fInextPageToken\fP nextPageToken or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBCollectionResponseRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.CollectionResponseRegistrationRecord\&.setNextPageToken (java\&.lang\&.String nextPageToken)"

.PP
\fBParameters:\fP
.RS 4
\fInextPageToken\fP nextPageToken or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
