.TH "com.example.lusifer.myapplication.backend.messaging.Messaging.MessagingEndpoint.SendMessage" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.messaging.Messaging.MessagingEndpoint.SendMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequest< Void >\fP, and \fBcom\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequest< Void >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendMessage\fP \fBsetAlt\fP (java\&.lang\&.String alt)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetFields\fP (java\&.lang\&.String fields)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetKey\fP (java\&.lang\&.String key)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetOauthToken\fP (java\&.lang\&.String oauthToken)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetPrettyPrint\fP (java\&.lang\&.Boolean prettyPrint)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetQuotaUser\fP (java\&.lang\&.String quotaUser)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetUserIp\fP (java\&.lang\&.String userIp)"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetMessage\fP (java\&.lang\&.String message)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBset\fP (String parameterName, Object value)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetAlt\fP (java\&.lang\&.String alt)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetFields\fP (java\&.lang\&.String fields)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetKey\fP (java\&.lang\&.String key)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetOauthToken\fP (java\&.lang\&.String oauthToken)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetPrettyPrint\fP (java\&.lang\&.Boolean prettyPrint)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetQuotaUser\fP (java\&.lang\&.String quotaUser)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetUserIp\fP (java\&.lang\&.String userIp)"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsetMessage\fP (java\&.lang\&.String message)"
.br
.ti -1c
.RI "\fBSendMessage\fP \fBset\fP (String parameterName, Object value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSendMessage\fP (java\&.lang\&.String message)"
.br
.ti -1c
.RI "\fBSendMessage\fP (java\&.lang\&.String message)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.Messaging\&.MessagingEndpoint\&.SendMessage\&.SendMessage (java\&.lang\&.String message)\fC [protected]\fP"
Create a request for the method 'messagingEndpoint\&.sendMessage'\&.
.PP
This request holds the parameters needed by the the messaging server\&. After setting any optional parameters, call the \fBSendMessage#execute()\fP method to invoke the remote operation\&. 
.PP
\fBSendMessage#initialize(com\&.google\&.api\&.client\&.googleapis\&.services\&.AbstractGoogleClientRequest)\fP must be called to initialize this instance immediately after invoking the constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.13 
.RE
.PP

.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.Messaging\&.MessagingEndpoint\&.SendMessage\&.SendMessage (java\&.lang\&.String message)\fC [protected]\fP"
Create a request for the method 'messagingEndpoint\&.sendMessage'\&.
.PP
This request holds the parameters needed by the the messaging server\&. After setting any optional parameters, call the \fBSendMessage#execute()\fP method to invoke the remote operation\&. 
.PP
\fBSendMessage#initialize(com\&.google\&.api\&.client\&.googleapis\&.services\&.AbstractGoogleClientRequest)\fP must be called to initialize this instance immediately after invoking the constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.13 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
