.TH "com.example.lusifer.myapplication.backend.RegistrationRecord" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.RegistrationRecord \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetRegId\fP ()"
.br
.ti -1c
.RI "void \fBsetRegId\fP (String regId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Objectify object model for device registrations we are persisting 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
