.TH "com.example.lusifer.myapplication.backend.messaging.MessagingRequestInitializer" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.messaging.MessagingRequestInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CommonGoogleJsonClientRequestInitializer, and CommonGoogleJsonClientRequestInitializer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessagingRequestInitializer\fP (String key)"
.br
.ti -1c
.RI "\fBMessagingRequestInitializer\fP (String key, String userIp)"
.br
.ti -1c
.RI "final void \fBinitializeJsonRequest\fP (com\&.google\&.api\&.client\&.googleapis\&.services\&.json\&.AbstractGoogleJsonClientRequest<?> request)  throws java\&.io\&.IOException "
.br
.ti -1c
.RI "\fBMessagingRequestInitializer\fP (String key)"
.br
.ti -1c
.RI "\fBMessagingRequestInitializer\fP (String key, String userIp)"
.br
.ti -1c
.RI "final void \fBinitializeJsonRequest\fP (com\&.google\&.api\&.client\&.googleapis\&.services\&.json\&.AbstractGoogleJsonClientRequest<?> request)  throws java\&.io\&.IOException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitializeMessagingRequest\fP (\fBMessagingRequest\fP<?> request)  throws java\&.io\&.IOException "
.br
.ti -1c
.RI "void \fBinitializeMessagingRequest\fP (\fBMessagingRequest\fP<?> request)  throws java\&.io\&.IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Override public void initializeMessagingRequest(\fBMessagingRequest\fP{ <}?{ >} request) throws IOException { // custom logic } } 
.PP
Subclasses should be thread-safe\&. 
.PP
\fBSince:\fP
.RS 4
1\&.12 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.MessagingRequestInitializer (String key)"

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP API key or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.RE
.PP

.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.MessagingRequestInitializer (String key, String userIp)"

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP API key or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.br
\fIuserIp\fP user IP or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.RE
.PP

.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.MessagingRequestInitializer (String key)"

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP API key or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.RE
.PP

.SS "com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.MessagingRequestInitializer (String key, String userIp)"

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP API key or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.br
\fIuserIp\fP user IP or
.PP
.nf
null 

.fi
.PP
 to leave it unchanged 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.initializeMessagingRequest (\fBMessagingRequest\fP<?> request) throws java\&.io\&.IOException\fC [protected]\fP"
Initializes \fBMessaging\fP request\&.
.PP
Default implementation does nothing\&. Called from \fBinitializeJsonRequest(com\&.google\&.api\&.client\&.googleapis\&.services\&.json\&.AbstractGoogleJsonClientRequest)\fP\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIjava\&.io\&.IOException\fP I/O exception 
.RE
.PP

.SS "void com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.MessagingRequestInitializer\&.initializeMessagingRequest (\fBMessagingRequest\fP<?> request) throws java\&.io\&.IOException\fC [protected]\fP"
Initializes \fBMessaging\fP request\&.
.PP
Default implementation does nothing\&. Called from \fBinitializeJsonRequest(com\&.google\&.api\&.client\&.googleapis\&.services\&.json\&.AbstractGoogleJsonClientRequest)\fP\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIjava\&.io\&.IOException\fP I/O exception 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
