.TH "com.example.lusifer.myapplication.backend.registration.model.RegistrationRecord" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.registration.model.RegistrationRecord \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GenericJson, and GenericJson\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java\&.lang\&.String \fBgetRegId\fP ()"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBsetRegId\fP (java\&.lang\&.String regId)"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBset\fP (String fieldName, Object value)"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBclone\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetRegId\fP ()"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBsetRegId\fP (java\&.lang\&.String regId)"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBset\fP (String fieldName, Object value)"
.br
.ti -1c
.RI "\fBRegistrationRecord\fP \fBclone\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Model definition for \fBRegistrationRecord\fP\&.
.PP
This is the Java data model class that specifies how to parse/serialize into the JSON that is transmitted over HTTP when working with the registration\&. For a detailed explanation see: \fChttp://code\&.google\&.com/p/google-http-java-client/wiki/JSON\fP 
.PP
\fBAuthor:\fP
.RS 4
Google, Inc\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "java\&.lang\&.String com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.RegistrationRecord\&.getRegId ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "java\&.lang\&.String com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.RegistrationRecord\&.getRegId ()"

.PP
\fBReturns:\fP
.RS 4
value or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.RegistrationRecord\&.setRegId (java\&.lang\&.String regId)"

.PP
\fBParameters:\fP
.RS 4
\fIregId\fP regId or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP

.SS "\fBRegistrationRecord\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.registration\&.model\&.RegistrationRecord\&.setRegId (java\&.lang\&.String regId)"

.PP
\fBParameters:\fP
.RS 4
\fIregId\fP regId or
.PP
.nf
null 

.fi
.PP
 for none 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
