.TH "com.example.lusifer.myapplication.backend.messaging.Messaging.MessagingEndpoint" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.messaging.Messaging.MessagingEndpoint \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSendMessage\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendMessage\fP \fBsendMessage\fP (java\&.lang\&.String message)  throws java\&.io\&.IOException "
.br
.ti -1c
.RI "\fBSendMessage\fP \fBsendMessage\fP (java\&.lang\&.String message)  throws java\&.io\&.IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
The 'messagingEndpoint' collection of methods\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSendMessage\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.Messaging\&.MessagingEndpoint\&.sendMessage (java\&.lang\&.String message) throws java\&.io\&.IOException"
Create a request for the method 'messagingEndpoint\&.sendMessage'\&.
.PP
This request holds the parameters needed by the messaging server\&. After setting any optional parameters, call the \fBSendMessage#execute()\fP method to invoke the remote operation\&.
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the request 
.RE
.PP

.SS "\fBSendMessage\fP com\&.example\&.lusifer\&.myapplication\&.backend\&.messaging\&.Messaging\&.MessagingEndpoint\&.sendMessage (java\&.lang\&.String message) throws java\&.io\&.IOException"
Create a request for the method 'messagingEndpoint\&.sendMessage'\&.
.PP
This request holds the parameters needed by the messaging server\&. After setting any optional parameters, call the \fBSendMessage#execute()\fP method to invoke the remote operation\&.
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the request 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
