.TH "com.example.lusifer.myapplication.backend.OfyService" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.OfyService \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Objectify \fBofy\fP ()"
.br
.ti -1c
.RI "static ObjectifyFactory \fBfactory\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Objectify service wrapper so we can statically register our persistence classes More on Objectify here : https://code.google.com/p/objectify-appengine/ 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
