.TH "com.example.lusifer.myapplication.backend.messaging.MessagingRequest< T >" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.lusifer.myapplication.backend.messaging.MessagingRequest< T > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBMessaging\fP request\&.
.PP
\fBSince:\fP
.RS 4
1\&.3 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
