.TH "DB_Connect" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Connect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP ()"
.br
.ti -1c
.RI "\fBclose\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
