.TH "DB_Functions" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Functions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstoreUser\fP ($gcm_regid)"
.br
.ti -1c
.RI "\fBgetAllUsers\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "DB_Functions::getAllUsers ()"
Getting all users 
.SS "DB_Functions::storeUser ( $gcm_regid)"
Storing new user returns user details 

.SH "Author"
.PP 
Generated automatically by Doxygen for Antardhwani from the source code\&.
