.TH "app/src/main/java/antardhvani/du/ac/in/Gyanodaya Directory Reference" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/main/java/antardhvani/du/ac/in/Gyanodaya Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGyanodaya\&.java\fP"
.br
.in -1c
