.TH "backend/build/tmp/appengineEndpointsExpandClientLibs/registration-v1-java.zip-unzipped/registration/src/main/java/com/example/lusifer/myapplication/backend/registration Directory Reference" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/build/tmp/appengineEndpointsExpandClientLibs/registration-v1-java.zip-unzipped/registration/src/main/java/com/example/lusifer/myapplication/backend/registration Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmodel\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBRegistration\&.java\fP"
.br
.ti -1c
.RI "file \fBRegistrationRequest\&.java\fP"
.br
.ti -1c
.RI "file \fBRegistrationRequestInitializer\&.java\fP"
.br
.ti -1c
.RI "file \fBRegistrationScopes\&.java\fP"
.br
.in -1c
