.TH "gcm_server Directory Reference" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gcm_server Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.php\fP"
.br
.ti -1c
.RI "file \fBdb_connect\&.php\fP"
.br
.ti -1c
.RI "file \fBdb_functions\&.php\fP"
.br
.ti -1c
.RI "file \fBGCM\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBregister\&.php\fP"
.br
.ti -1c
.RI "file \fBsend_message\&.php\fP"
.br
.ti -1c
.RI "file \fBtest\&.php\fP"
.br
.in -1c
