.TH "backend/build/generated-source/endpoints/java/com/example/lusifer Directory Reference" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/build/generated-source/endpoints/java/com/example/lusifer Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmyapplication\fP"
.br
.in -1c
