.TH "backend/build/generated-source/endpoints/java/com/example/lusifer/myapplication/backend/messaging Directory Reference" 3 "Fri May 29 2015" "Version 0.1" "Antardhwani" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/build/generated-source/endpoints/java/com/example/lusifer/myapplication/backend/messaging Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMessaging\&.java\fP"
.br
.ti -1c
.RI "file \fBMessagingRequest\&.java\fP"
.br
.ti -1c
.RI "file \fBMessagingRequestInitializer\&.java\fP"
.br
.ti -1c
.RI "file \fBMessagingScopes\&.java\fP"
.br
.in -1c
